# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_NFS_RUST_SAMPLE_MINIMAL)		+= nfs3.o nfsd.o
obj-$(CONFIG_NFS_RUST_SAMPLE_PRINT)			+= rust_nfs_print.o

subdir-$(CONFIG_NFS_SAMPLE_RUST_HOSTPROGS)		+= hostprogs
